### ISSUE TITLE
Initial mobility set up - error

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#14]
I just installed the mobility then opted to do a '5 min' sampling interval at 6:59 am. The first log shows 'error - 6:59 am' then followed by 'still - 7:00am'. It should have been 'still - 6:59 am' then followed by 'still - 7:04 am'.

**Comment by cketcham** [comment]
moved issue to MobilityPhone https://github.com/cens/MobilityPhone/issues/20
