### ISSUE TITLE
Location reminder is not triggered when reaching the location.

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#20]
I set up a location reminder (parking lot 9) to trigger always. I tested both the actual phone and on the emulator (2.3) but the notification didn't trigger when I reached the location (34.067458, -118.443756).

**Comment by ctrance** [comment]
03-25 20:04:33.878: D/LocTrigService(717): LocTrigService: Handling GPS sample alarm
03-25 20:04:33.888: D/LocTrigService(717): LocTrigService: Stopping motion detection...
03-25 20:04:33.908: D/LocTrigService(717): LocTrigService: Turning on location updates
03-25 20:04:33.928: D/LocTrigService(717): LocTrigService: Setting alarm: org.ohmage.triggers.types.location.LocTrigService.GPS_TIMEOUT
03-25 20:04:33.938: D/SelectionBuilder(717): query(columns=null) SelectionBuilder[table=campaigns, selection=(campaign_status=0), selectionArgs=[]]
03-25 20:04:34.118: D/dalvikvm(98): GC_CONCURRENT freed 629K, 51% free 5134K/10439K, external 816K/1328K, paused 10ms+16ms
03-25 20:04:34.138: D/TriggerFramework(717): TriggerBase: getAllActiveTriggerIds()
03-25 20:04:34.148: D/TriggerFramework(717): DB: open
03-25 20:04:34.168: D/TriggerFramework(717): DB: getTriggers(LocationTrigger)
03-25 20:04:34.178: D/TriggerFramework(717): DB: close
03-25 20:04:36.298: D/SntpClient(98): request time failed: java.net.SocketException: Address family not supported by protocol
03-25 20:05:19.018: D/LocTrigService(717): LocTrigService: Handling GPS timeout
03-25 20:05:19.028: D/LocTrigService(717): LocTrigService: Unable to obtain samples. Timing out
03-25 20:05:19.038: D/LocTrigService(717): LocTrigService: Current speed: 0.0
03-25 20:05:19.048: D/LocTrigService(717): LocTrigService: Turning off location updates
03-25 20:05:19.078: D/LocTrigService(717): LocTrigService: Proximity dist: 1.2601994E7
03-25 20:05:19.078: D/LocTrigService(717): LocTrigService: Sleep time updated to: 360000
03-25 20:05:19.088: D/LocTrigService(717): LocTrigService: Setting alarm: org.ohmage.triggers.types.location.LocTrigService.GPS_SAMPLE
03-25 20:05:19.108: D/LocTrigService(717): LocTrigService: Starting motion detection...
03-25 20:05:19.108: W/ActivityManager(98): Unable to start service Intent { act=edu.ucla.cens.wifigpslocation.IWiFiGPSLocationService }: not found
03-25 20:05:19.118: W/ActivityManager(98): Unable to start service Intent { act=edu.ucla.cens.accelservice.IAccelService }: not found
03-25 20:05:19.118: D/SelectionBuilder(717): query(columns=null) SelectionBuilder[table=campaigns, selection=(campaign_status=0), selectionArgs=[]]
03-25 20:05:19.138: D/TriggerFramework(717): TriggerBase: getAllActiveTriggerIds()
03-25 20:05:19.148: D/TriggerFramework(717): DB: open
03-25 20:05:19.168: D/TriggerFramework(717): DB: getTriggers(LocationTrigger)
03-25 20:05:19.178: D/TriggerFramework(717): DB: close
03-25 20:06:04.447: D/SelectionBuilder(717): query(columns=null) SelectionBuilder[table=campaigns, selection=(campaign_status=0), selectionArgs=[]]
03-25 20:06:04.487: D/TriggerFramework(717): TriggerBase: getAllActiveTriggerIds()
03-25 20:06:04.497: D/TriggerFramework(717): DB: open
03-25 20:06:04.507: D/TriggerFramework(717): DB: getTriggers(LocationTrigger)
03-25 20:06:04.517: D/TriggerFramework(717): DB: close
03-25 20:08:06.848: D/LocTrigMapsActivity(717): Maps: onStop
03-25 20:08:06.848: D/LocTrigMapsActivity(717): Maps: stopGPS
03-25 20:08:06.868: D/LocTrigMapsActivity(717): Maps: onDestroy
03-25 20:08:06.888: D/LocTrigMapsActivity(717): Maps: stopGPS

**Comment by jshslsky** [comment]
The version of location reminders in ohmage is not always accurate. The best fix for this is to upgrade to Google's location services and we'll be doing that in a future release.
