### ISSUE TITLE
Evaluate current probe architecture

### ISSUE THREAD

**Issue by cketcham** [ohmage/android-lib#22]
We may have to do some redesign to the probe architecture so it is more tolerant of application crashes. Because there can be some time between sending a probe, receiving it at the probe manager and saving to the db, if a probe crashes the point can be lost.

Three options which could potentially fix the issue:
- ACK the data, and resend points that aren't received. This may still not work if the probe crashes and looses the point itself.
- use the oneway keyword to guarantee probes are sent immediately to ohmage
- stop buffering the data

**Comment by cketcham** [comment]
checked the data from mobility for the past two weeks and it matches the number of points on the server exactly. (Running on Nexus 4)

**Comment by jshslsky** [comment]
We have verified that any inconsistency was the result of a third-party app (e.g., Mobility) crashing.

See this updated server issue: https://github.com/cens/ohmageServer/issues/587
