### ISSUE TITLE
Tapping notification didn't open the pending survey page 

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#27]
I created a time reminder on 2.2 android emulator (Target: Google API) then restarted the device. The reminder still triggered at the set time but when I tapped the campaign on the notification, I wasn't redirected to the pending survey page.

**Comment by cketcham** [comment]
Can you describe the exact steps to reproduce this? Does this always happen to you? I can't seem to get this to happen.

**Comment by ctrance** [comment]
I just retested and is working now, must be a bug from the emulator.
