### ISSUE TITLE
Pending (survey filter) doesn't show counter.

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#33]
On test case no.84 (https://docs.google.com/spreadsheet/ccc?key=0AuPU77vjksOAdFVqSWFqb0s4c3haWWc3Z3lDMmdTVlE#gid=5), it's stated that there should be a number/counter right next to the 'Pending' filter but no counter shows.

**Comment by jshslsky** [comment]
@cketcham since this isn't implemented, can you make sure it is removed from the spreadsheet?

**Comment by cketcham** [comment]
I removed it
