### ISSUE TITLE
Reminder will never be triggered if phone was off during the trigger time

### ISSUE THREAD

**Issue by cketcham** [ohmage/android-lib#34]
The trigger which happened while the phone was off should be shown in the notification bar once the phone is restarted (as long as the notification duration has not been passed)

**Comment by ctrance** [comment]
This remains an issue on 2.16.

**Comment by jshslsky** [comment]
We are thinking about this. In the case where the phone was off for many days and the user had a few reminders per day, showing all of the reminders when the phone was turned on would be annoying. 

For shorter time frames, we can store the last time a reminder fired and if the phone was only off for 24 hours or so.

We won't fix for 2.16, but we'll look at it for 3.0.
