### ISSUE TITLE
Single Campaign Mode shows incorrect dashboard.

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#35]
The expected items on the dashboard (accdg. to the test plan) are only survey, mobility and help for single campaign mode but Response History, Upload Queue, Profile, and Streams are showing.

**Comment by ctrance** [comment]
The response history button (calendar icon) shows on Survey Info page too.

**Comment by cketcham** [comment]
Those tests were actually incorrect. It should actually be changed by the setting "Show Feedback" in the admin settings. I removed the previous testing results on the test plan. please retest with the updated test plan.

**Comment by ctrance** [comment]
Behaving as expected on the new test case. I'm closing this issue.
