### ISSUE TITLE
Notification Duration and Suppression window shows incorrect ranges

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#40]
The test case says the correct range for Notification Duration and Suppression window is 0-60 but below are the ranges that show on 'Notification Settings'

Notification duration: 1-1440
Suppression window: 0-1140

**Comment by cketcham** [comment]
We actually changed this without updating the test cases. fixed on the test cases

**Comment by ctrance** [comment]
This is not an issue anymore, Notification duration & Suppression window are validating as expected.
