### ISSUE TITLE
Remind again didn't go off after deleting the other set time

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#41]
I set up (2) 'remind again', a 5-min and a 10-min. The (2) remind again go off correctly on the phone then I deleted the 10-min but kept the 5-min. The last reminder was triggered on 3:03 pm but by 3:08 (even waited till 3:11 pm) the reminder didn't go off as if I deleted all 'remind again'.

**Comment by cketcham** [comment]
What was the exact sequence of steps for creating reminders, creating remind again times, and removing the remind again times?

**Comment by ctrance** [comment]
1. Created a time reminder to go off on 2:53 pm.
2. Added 'remind again' 5 mins.
3. Added 'remind again' 10 mins.
4. At 2:53, 2:58, & 3:03 reminder go off.
5. At 3:04, I deleted 10-mins 'remind again' but kept the 5-mins.

**Comment by cketcham** [comment]
The remind again times calculates the new time to show a notification based on the original time of the notification. So if you have two remind again times for 5 and 10 minutes, and a reminder set for 2:53, you will get notifications at 2:53, 2:58 and 3:03. If you go and change the remind again times, it recalculates the offsets based on the time of the original notification.

So in this case even though you went back to the settings and deleted the 10 mins 'remind again', the 5 min 'remind again' had already gone off at 3:03. If you had wanted a reminder to go off at 3:08, you would have needed to make a 15 min remind again time (15 minutes after 2:53 is 3:08).

Does that make sense?

**Comment by ctrance** [comment]
So basically the remaining 5 mins 'remind again' is useless, I thought it will recalculate based on the last trigger. I'll test your scenario above.

**Comment by cketcham** [comment]
yeah in that case it would be. but if you had another reminder go off in the future (say at 3:10), then the 5 minute remind again would give another reminder (at 3:15). And since you deleted the 10 minute remind again, a reminder will not go off in 10 minutes (at 3:20).

**Comment by ctrance** [comment]
The remind again edit/delete is behaving as expected, it's calculating based on the original time of the notification.
