### ISSUE TITLE
Notification setting doesn't affect the other campaign

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#43]
On campaign A I set the notification setting as 'Notification duration=5 mins/Remind again=2 mins". I went to campaign B just to make sure the notification setting there changes too, it did but after 2 mins only campaign A reminder go off. I waited for 6 mins and still campaign B reminder didn't go off. Also after 5 mins, the notification for campaign A also cleared from the notification list but the notification for campaign B (the initial reminder) still remain on the notification list.

**Comment by cketcham** [comment]
What were your exact steps for changing the notification settings and creating reminders?

**Comment by ctrance** [comment]
@cketcham - I might have used the same scenario as #41. After retesting, the notification setting is behaving correctly for both campaign A & B.
