### ISSUE TITLE
Add Audio prompt type

### ISSUE THREAD

**Issue by cketcham** [ohmage/android-lib#48]
we want to allow users to record audio as a prompt type like video or images

**Comment by jshslsky** [comment]
Server issue: cens/ohmageServer#540

**Comment by jshslsky** [comment]
For older phones (2.2, 2.3), the audio format will be AMR, but the code can be smart enough to figure out the best quality file format.

**Comment by jojenki** [comment]
What fields seem appropriate here? max_duration?

**Comment by cketcham** [comment]
I think that makes sense.

**Comment by jshslsky** [comment]
I'd say the global file size limit is appropriate. There isn't a way to figure out the max duration unless you introspect on the file type, bit rate, etc.

**Comment by jojenki** [comment]
@cketcham In the same way you can limit video duration, can you limit audio duration?

**Comment by jojenki** [comment]
It looks like there are a couple ways to do it: http://stackoverflow.com/questions/9321380/how-to-automatically-limit-android-audio-recording-length
