### ISSUE TITLE
Add decimal prompt type

### ISSUE THREAD

**Issue by cketcham** [ohmage/android-lib#49]
We want to allow decimal input as a prompt type

**Comment by jshslsky** [comment]
Server issue: cens/ohmageServer#539

If both min and max are whole numbers, show the increment buttons. If either min or max are floats, do not show the increment buttons. The input will be restricted by the number of allowed significant digits.

**Comment by cketcham** [comment]
For now we are going to see how we like keeping + and - and just having them inc or dec by 1
