### ISSUE TITLE
Add images to prompt questions

### ISSUE THREAD

**Issue by cketcham** [ohmage/android-lib#50]
We want to allow prompt questions to include images that are displayed on the phone when a user is taking a survey.

**Comment by jshslsky** [comment]
We'll have to figure out the best way to do this for each prompt type. It seems like number, text, timestamp, audio, photo and video can all be handled uniformly. Then for the choice types, the images will be for each choice. 

If the image cannot be loaded, there will have to be text to display.

**Comment by hongsudt** [comment]
so we should come up with a tag name, and I think it should also handle
multiple images..

**Comment by cketcham** [comment]
we could do something like Markdown uses `![Alt text](/path/to/img.jpg "Optional title")`

**Comment by jshslsky** [comment]
It seems like that would work and it wouldn't cause an XML parser to choke. Is there a Markdown lib for Android?

**Comment by jojenki** [comment]
I'm not sure which is best, but we could always use the HTML tag, "img". If you are already using a XML parser, then adding a XPath query of "//img" would easily find all of the image tags.

**Comment by hongsudt** [comment]
I need to learn a little bit more about markdown.. But one of the cons of
using this approach would be inconsistency in the config. If we go with
tags, it is consistent with the rest and doesn't require the campaign
author to understand another syntax.

**Comment by jojenki** [comment]
Yes, but if we ever want to move away from XML, e.g. JSON, then having a more "universal" way of describing them would be better. It would be odd to have an "img" tag in the middle of some JSON string.

On the other hand, JSON already has a way to accomplish this using something that would not exist in any other language.

**Comment by jshslsky** [comment]
How about 

```
<properties>
    <imageUrl>http://example.com</imageUrl>
</properties>
```

?

I don't think we should allow for more than one image.

**Comment by jshslsky** [comment]
@cketcham when you show the image will you just auto-scale?

**Comment by jojenki** [comment]
I was thinking directly in the text:

```
<property>
  <key>0</key>
  <label><img src="http://example.com/myImage.png"/></label>
</property>
```

**Comment by jshslsky** [comment]
That will only work for choice prompt types and it will break if someone wants both a label and an image.

**Comment by hongsudt** [comment]
Can we think of a solution that allows multiple images?  at least at the
question level..

**Comment by jshslsky** [comment]
Can you provide an example use case?

If we allow multiple images, issues like ordering come up.

**Comment by hongsudt** [comment]
The order of images can be based on the order in the xml..

Examples:
Comparing the first image with the second image, what are the difference?
Or for a message type, display multiple images as an intervention when you
feel stress..

**Comment by jojenki** [comment]
@joshuaselsky The text and the image can be put together, e.g.

```
<property>
  <key>0</key>
  <label>This is some text before. <img src="http://example.com/myImage.png"/> And, this is some text after.</label>
</property>
```

Although, this leads to rendering issues no matter if you use Markdown or HTML tags.

**Comment by jojenki** [comment]
@hongsudt I think @joshuaselsky was simply referring to not allowing multiple images for, say, a single choice in a choice prompt. For example, a single choice prompt whose question is some text and _one_, of many, choices is:

```
<property>
  <key>0</key>
  <label><img src="http://example.com/image1.png"/><img src="http://example.com/image2.png"/></label>
</property>
```

It would render it like an web page would render it where one image follows the other.

I am not sure that this is worth explicitly disallowing. I think common sense will tell most people not to do it, but I see no reason to spend time creating the exception now only to potentially remove it later when a valid use-case comes up.

**Comment by cketcham** [comment]
I agree with @jojenki. I don't see any reason to disallow more than one image.

I also am wondering about the format of how to define an image tag. I am still in favor of doing something more like Markdown rather than using an xml image tag. I think it is more confusing to use xml in the label text because this use is different than all other xml in the document. This embedded image is more like styling the text and the other xml is for structuring the campaign.

**Comment by jshslsky** [comment]
OK, the multiple image use case makes sense. Thanks @hongsudt. For the styling I agree with @cketcham. If we use Markdown (very easy to learn), it will avoid cases where a campaign author could accidentally create XML that is not well-formed. Markdown is also interesting because we could have "label" text that includes bulleted lists. Probably should just support images for now. 

@hongsudt here is a quick guide to [Markdown](http://daringfireball.net/projects/markdown/syntax).

**Comment by jshslsky** [comment]
@jeroenooms how hard would it be to either (1) show an image on the axes or (2) show the alt text. We want to include images in the promptText and label elements and we are wondering how this will impact your visualizations?

**Comment by jeroen** [comment]
@joshuaselsky I don't get your question. Which application are you talking about? From what I understand, this issue is about displaying the question, not the response?

**Comment by jshslsky** [comment]
@jeroenooms For any of the choice prompt types an image can be in the content of the each choice's label element. That is where we suspect you might be impacted.

**Comment by jeroen** [comment]
Oh. Hmm yes that is a bit problematic. I would have preferred to keep the label plain text, and put any markup language (being it html, markdown) in a separate tag. Has it already been implemented?

**Comment by jshslsky** [comment]
No, this is why we asked you first. 

How about `<imageLabel>` @cketcham @hongsudt?

**Comment by jeroen** [comment]
I also would suggest not to mix `html` with `xml`. The thing above is a bit dangerous, because the `<img>` will be treated as a node in the campaign definition during the initial xml parsing. 

So perhaps you want to put the contents of `<imageLabel>` inside a `<![CDATA[` tag?

**Comment by cketcham** [comment]
I thought we were using markdown for both the prompt text and choice label to specify images

**Comment by jeroen** [comment]
Oh okay that makes sense. I read over the discussion too quickly. But perhaps we should still use `CDATA` for the markdown? Just in case the markdown contains characters that could be interpreted as `xml` ?

**Comment by jshslsky** [comment]
Cameron and I just discussed this here and I think we'll use a new element called `<longLabel>` and leave `<label>` alone. If the Android app finds a longLabel element, it can render that and then fallback to label.

**Comment by jeroen** [comment]
Still it would be a good idea to establish some proper way of embedding an alternative language inside the XML. So you either need to make sure the contents will never contain xml reserved characters, or use `CDATA`.

Also, it is not unthinkable there in the future other use cases would arise where we want to embed some markup language elsewhere. So perhaps you want to have some general way of marking a node with a certain content-type, to give clients a hint on how to display things. 

So for example something like `<longLabel type="x-markdown">`. What you want to avoid is a document containing a mix of xml, json, markdown, etc and then requiring the developer to dig though documentation to figure out which nodes contain what. Or maybe I am over thinking this.

**Comment by hongsudt** [comment]
I like this solution.. so that there will be minimum impact to the
front-end and ocpu.. The front-end can implement the support for
<longLabel> later..

I am not sure I like <longLabel>, but since I don't have any better term,
we will go with it.

**Comment by jojenki** [comment]
Looking ahead for 3.0, is this the solution we want to go with? If backwards compatibility weren't an issue, what would be the optimal solution?

**Comment by jeroen** [comment]
@hongsuda perhaps `<markdownLabel>` would be better, to emphasize both to the campaign author and campaign consumer that this node must contain markdown.

**Comment by jeroen** [comment]
@jojenki as stated above, it would be nice to define a unified way to embed non-xml fragments in our document, e.g. json, javascript, markdown, etc. It would be great if we could use some standard mime `content-type` codes to identify such embedded code.

Atom does something similar for embedding html/xhtml: http://www.xml.com/lpt/a/1633.

**Comment by jshslsky** [comment]
For 3.0, we will define campaigns using Concordia, so this would become a JSON String.

I like `<markdownLabel>`.

**Comment by hongsudt** [comment]
I also like markdownLabel

@jeroenooms  We are planning to support the same markdown on the prompt question as well. Will this affect your viz (i.e. ocpu and snackboard)?

**Comment by jeroen** [comment]
That depends on if the output from `survey_response/read` will be affected. The viz (opencpu and dashboard) don't directly read the XML anywhere; the prompt names and labels are identified via `survey_response/read`, using column-wise and csv output, respectively.

**Comment by hongsudt** [comment]
@jojenki @joshuaselsky  Do you guys plan to handle this on the backend? Or should Jeroen's handle it?

**Comment by jeroen** [comment]
Lets do the same as for the label, where we keep the original question text in plain text, and allow for an optional additional node with markdown format. We should not assume that all clients will be able to render markdown.

**Comment by jshslsky** [comment]
We don't need to return the value for `<markdownLabel>` from `survey_response/read`. That way this change will be completely transparent to all clients. The Android app reads the XML, so it will receive the entire contents with the new element included.

**Comment by jojenki** [comment]
My $0.02 is that, if the 2.x APIs are dying and we are going with a complete overhaul of the system for 3.0, then this solution seems perfectly valid. We can run it through the ringer for this and then, going forward, have a more comprehensive solution like @jeroenooms suggested.

**Comment by jshslsky** [comment]
We'll need to come up with guidelines for images so images can be rendered appropriately on devices with different pixel densities.
- Guidelines for Prompt Text images -- height and width
- Choices -- possibly just width?

**Comment by jshslsky** [comment]
@cketcham can you update the campaign definition page on the [ohmageServer wiki](https://github.com/cens/ohmageServer/wiki/Campaign-Definition)?
