### ISSUE TITLE
rename campaign to project in the UI only

### ISSUE THREAD

**Issue by jshslsky** [ohmage/android-lib#53]
The best approach would be something that allowed Mobilize to still use the word Campaign, but regular ohmage could use Project.

**Comment by cketcham** [comment]
If we don't upgrade mobilize to 2.15 or 2.16 this year, then we don't have a problem. Do we know what is happening next year? If changing the name from campaign to projects is fine for next year that would be easiest, but if not, it is an easy change to keep mobilize using the word campaigns.

**Comment by jshslsky** [comment]
Just to make sure I understand: would you just override the string with the word Campaign in the MobilizeApp repo?

**Comment by cketcham** [comment]
Yeah. I plan to change the references to campaigns in the res/values/strings.xml file. In the MobilizeApp repo, I can just override those specific values so it stays campaign.

**Comment by hongsudt** [comment]
For the next academic year (starting in aug), there is a chance that ohmage
will be used all year round by different classes.. I can try to pinpoint
this timeline and let you know.. But the plan is to use ohmage for data
collection in ECS, biology, science and stat classes.

**Comment by cketcham** [comment]
It's ok if we change campaigns to be projects for that? or will we need to continue to use campaigns.

**Comment by hongsudt** [comment]
I think Mobilize will continue to use "campaigns", but I can check whether
they are ok with the change.

my sense is that they would prefer not to change since we will need to
communicate the change to a large group of people which is extremely hard.
