### ISSUE TITLE
User is still logged in after failing of campaign download.

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#54]
Right after I logged in, I went to the phone’s setting and turned off my wi-fi (this is the only data connection I have)
I waited for 5 mins and went back to ohmage to see if the campaign has auto-downloaded
I’m still logged in, I was redirected to Sync Password (the last screen I was prior to turning off my data connection) instead of Login page after tapping ohmage on my phone. The campaign wasn’t downloaded though.

**Comment by cketcham** [comment]
This behavior will actually only happen during the initial log in. This is correct behavior if the "sync password" button is used. It should not change the campaign which is currently downloaded. I will need to give you a special apk which has singleCampaignMode set to true so it will log you in with single campaign mode the first time you log into the app.
