### ISSUE TITLE
Pilots.mobilizelabs deployment config is set to Admin mode=false but pin wasn't required

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#57]
I logged in to pilots.mobilizelabs where the deployment config sets Admin mode to false. Opening the setting didn't require for pin code, i'm using the latest version on web.ohmage.org/ohmage/apk

**Comment by cketcham** [comment]
What steps did you take when you were first logging into the server? I can't seem to reproduce this with the latest apk.

**Comment by ctrance** [comment]
Oops my bad, I thought it's on 'Settings' that the pin code prompt shows but it shows on accessing 'Admin Settings'. Sorry about that, I'll close this issue.
