### ISSUE TITLE
message tag not displayed

### ISSUE THREAD

**Issue by stevenolen** [ohmage/android-lib#58]
Steve's complex xml tests campaign, message tag survey.

No message alert is displayed -- don't have a moment to add logs, but didn't want to forget! :)

**Comment by cketcham** [comment]
what is it supposed to show? I see the timestamp prompt and then a message and thats it.

**Comment by cketcham** [comment]
@stevenolen what is the bug that you are experiencing?

**Comment by jshslsky** [comment]
@stevenolen, @cketcham has not been able to recreate this. Can you try again?

**Comment by stevenolen** [comment]
using otest with ohmage 2.16.3:

Steve's complex XML tests -> Message survey.  A message tag exists and is supposed to fire after answer the timestamp message, but does not (downloading the latest SDK tools now, can submit logs for this).

**Comment by stevenolen** [comment]
oh. it's no longer a pop-up "alert window". I get it now. can close. my mistake, sorry!
