### ISSUE TITLE
allow restriction for whole numbers only to number prompt type

### ISSUE THREAD

**Issue by jshslsky** [ohmage/android-lib#60]
Campaign authors should be able to restrict the number prompt type to whole numbers only.

**Comment by jojenki** [comment]
For my first-pass, I used the property key "wholeNumber", which must be a valid, case-insensitive boolean, e.g. "true", "True", "FALSE". It cannot be "yes" or "1" or anything like that.

**Comment by cketcham** [comment]
Seems that the server is case sensitive when trying add a new campaign
