### ISSUE TITLE
Images for responses are not cached on the sdcard

### ISSUE THREAD

**Issue by cketcham** [ohmage/android-lib#61]
On JellyBean the image only seems to be cached in memory. When the application is restarted, the image is no longer available.

On 2.2 the image isn't on the sdcard, but the cache persists when the application is restarted, but not if the phone is rebooted.

The ResponseSyncService attempts to download the images to a cache, but it looks like it does not actually cache the images at all. After downloading a campaign and waiting for the ResponseSyncService to stop, if airplane mode is turned on, the image will fail to load when looking at the ResponseInfoActivity.

**Comment by cketcham** [comment]
@jojenki It looks like the server sends no-cache in the headers for a call to app/image/read. Did we do this so private images wouldn't be cached on intermediate servers?

Since images will basically never change could we make the cache control private with max-age of a year? I think that should prevent intermediate caches from caching, but will still let the client cache.

I'm starting to use a library on the android client which reads this header to decide if it should use the disk cache. It would be nice if I didn't have to change the library to force it to cache even if it gets the no-cache header.

**Comment by jshslsky** [comment]
I have pushed a change to odev so @cketcham can test. The cache control header for /app/image/read is now Cache-Control:max_age=1051200, private. I won't commit until we do some testing.
