### ISSUE TITLE
Prevent rounding errors for number prompts by using BigDecimal to represent it at all times

### ISSUE THREAD

**Issue by cketcham** [ohmage/android-lib#63]
Need to check that storing the value in the db works, as well as creating the json response which is sent to the server.

**Comment by jojenki** [comment]
I am having an issue where my max value for a number prompt is, 2147483647. I then input a number like, 2147483646.999999999999999. The uploaded value was, 2.1474836479.

**Comment by cketcham** [comment]
ended up being due to server processing the code to json
