### ISSUE TITLE
"max" property over 2^31-1 for number prompt causes the prompt to not exist

### ISSUE THREAD

**Issue by jojenki** [ohmage/android-lib#65]
Create a number prompt whose "max" property is larger than 2147483647. The server will say the prompt is valid. When the phone reads the campaign, it appears that everything works. Then, when it is displaying the survey that prompt will be missing. I am not sure what will happen if it is the only prompt in the survey.

**Comment by cketcham** [comment]
actually fixed on latest version at http://web.ohmage.org/ohmage/apk/ but not in the play store version yet.
