### ISSUE TITLE
check for support for XML cruft - 2.14

### ISSUE THREAD

**Issue by jshslsky** [ohmage/android-lib#7]
See John's commits here: cens/ohmageServer#501

**Comment by cketcham** [comment]
The crash we experienced:

E/AndroidRuntime( 6736): FATAL EXCEPTION: main
E/AndroidRuntime( 6736): java.lang.IllegalArgumentException: Display type does not exist: null
E/AndroidRuntime( 6736):    at org.ohmage.conditionevaluator.DataPoint.setDisplayType(DataPoint.java:153)
E/AndroidRuntime( 6736):    at org.ohmage.activity.SurveyActivity.getPreviousResponses(SurveyActivity.java:914)
E/AndroidRuntime( 6736):    at org.ohmage.activity.SurveyActivity.access$1000(SurveyActivity.java:96)
E/AndroidRuntime( 6736):    at org.ohmage.activity.SurveyActivity$2.onClick(SurveyActivity.java:375)
E/AndroidRuntime( 6736):    at android.view.View.performClick(View.java:4204)
E/AndroidRuntime( 6736):    at android.view.View$PerformClick.run(View.java:17355)
E/AndroidRuntime( 6736):    at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime( 6736):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 6736):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 6736):    at android.app.ActivityThread.main(ActivityThread.java:5041)
E/AndroidRuntime( 6736):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6736):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 6736):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 6736):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime( 6736):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  389):   Force finishing activity org.ohmage/.activity.SurveyActivity

**Comment by cketcham** [comment]
I'll just remove any reference to the same fields rather than just ignoring the fact that they aren't there.

**Comment by jshslsky** [comment]
That seems like a wise choice. If we ever need to add them back, we will have a concrete use case that will likely differ from the previous usage anyway.

**Comment by hongsudt** [comment]
For curiosity, what caused the crash? New XML?

**Comment by jshslsky** [comment]
Yep.

**Comment by cketcham** [comment]
the fact that the prompt didn't have displayType set. even though we don't use it on the phone, it throws an exception if its not valid.
