### ISSUE TITLE
Prompt text image doesn't show on tablet

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#76]
On samsung galaxy note 8 (tablet 4.1.2), the image on timestamp prompt doesn't show. The image shows on the phone though (4.1.2)

<prompt>
<id>timestamp</id>
<promptTextMarkdown>What time is it? ![Ohmage Logo](https://dev.ohmage.org/web/images/theme-ohmage/dashboard-header-logo.png)</promptTextMarkdown>

**Comment by jshslsky** [comment]
Closing because the image will eventually load.
