### ISSUE TITLE
Audio response is throwing upload error

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#77]
I finished responding to 'Audio' survey then uploaded my response but I'm getting "an error occurred while trying attempting to upload this response".

Below is the log:
07-11 09:56:49.240: D/SelectionBuilder(2169): query(columns=[responses._id, response_uuid, response_date, response_time, response_timezone, response_location_status, response_location_latitude, response_location_longitude, response_location_provider, response_location_accuracy, response_location_time, responses.survey_id, response_survey_launch_context, response_json, responses.campaign_urn, campaign_created]) SelectionBuilder[table=responses inner join campaigns on campaigns.campaign_urn=responses.campaign_urn inner join surveys on surveys.survey_id=responses.survey_id and surveys.campaign_urn=responses.campaign_urn, selection=(response_status!=8 AND response_status!=0 AND response_status!=7), selectionArgs=[]]
07-11 09:56:49.260: D/SelectionBuilder(2169): update() SelectionBuilder[table=responses, selection=(response_status!=8 AND response_status!=0 AND response_status!=7), selectionArgs=[]]
07-11 09:56:49.280: D/SelectionBuilder(2169): query(columns=[responses._id, campaign_name, survey_title, response_time, response_timezone, responses.response_status, response_uuid]) SelectionBuilder[table=responses inner join campaigns on campaigns.campaign_urn=responses.campaign_urn inner join surveys on surveys.survey_id=responses.survey_id and surveys.campaign_urn=responses.campaign_urn, selection=(responses.response_status!=0 AND responses.response_status!=8), selectionArgs=[]]
07-11 09:56:49.280: D/SelectionBuilder(2169): update() SelectionBuilder[table=responses, selection=(responses._id=?), selectionArgs=[339]]
07-11 09:56:49.310: D/UploadService(2169): Response uploaded with network location
07-11 09:56:49.320: D/SelectionBuilder(2169): query(columns=[prompt_response_value, survey_prompt_type]) SelectionBuilder[table=prompt_responses inner join responses on prompt_responses.response_id=responses._id, (select \* from survey_prompts where survey_prompts.composite_id=composite_id) SQ, selection=(SQ.composite_id=prompt_responses.composite_id) AND (SQ.prompt_id=prompt_responses.prompt_id) AND (responses._id=?) AND (prompt_response_value!=? AND prompt_response_value!=? AND (survey_prompt_type=? OR survey_prompt_type=? OR survey_prompt_type=?)), selectionArgs=[339, SKIPPED, NOT_DISPLAYED, photo, video, audio]]
07-11 09:56:49.380: D/SelectionBuilder(2169): query(columns=[responses._id, campaign_name, survey_title, response_time, response_timezone, responses.response_status, response_uuid]) SelectionBuilder[table=responses inner join campaigns on campaigns.campaign_urn=responses.campaign_urn inner join surveys on surveys.survey_id=responses.survey_id and surveys.campaign_urn=responses.campaign_urn, selection=(responses.response_status!=0 AND responses.response_status!=8), selectionArgs=[]]
07-11 09:56:49.810: D/dalvikvm(784): GC_EXPLICIT freed 4K, 49% free 2911K/5703K, external 1625K/2137K, paused 102ms
07-11 09:56:51.890: D/OhmageApi(2169): HTTP/1.1 200 OK
07-11 09:56:51.910: D/OhmageApi(2169): result: failure
07-11 09:56:51.920: D/OhmageApi(2169): {"result":"failure","errors":[{"text":"General server error.","code":"0100"}]}
07-11 09:56:51.930: D/OhmageApi(2169): Failed due to error codes: [0100]
07-11 09:56:51.940: D/SelectionBuilder(2169): update() SelectionBuilder[table=responses, selection=(responses._id=?), selectionArgs=[339]]
07-11 09:56:52.000: D/SelectionBuilder(2169): query(columns=[responses._id, campaign_name, survey_title, response_time, response_timezone, responses.response_status, response_uuid]) SelectionBuilder[table=responses inner join campaigns on campaigns.campaign_urn=responses.campaign_urn inner join surveys on surveys.survey_id=responses.survey_id and surveys.campaign_urn=responses.campaign_urn, selection=(responses.response_status!=0 AND responses.response_status!=8), selectionArgs=[]]
07-11 09:56:56.140: W/GTalkService(216): [GTalkConnection.23] doConnect: caught XMPPError connecting to mtalk.google.com:5228.: (502)
07-11 09:56:56.140: W/GTalkService(216):   -- caused by: java.net.SocketTimeoutException: Connection timed out
07-11 09:56:56.140: D/GTalkService(216): [GTalkConnection.23] connectionClosed: connId=0, error=CONNECTION FAILED
07-11 09:57:00.000: D/SampleReceiver(534): Start mobility service

**Comment by cketcham** [comment]
this was a server issue that was fixed.
