### ISSUE TITLE
upload ohmage to the amazon Android store

### ISSUE THREAD

**Issue by jshslsky** [ohmage/android-lib#78]
Not at all a priority, but this would be good to do. amazon also has this new feature where you can test drive an app.

**Comment by cketcham** [comment]
wow the test drive thing is cool.. I wonder how that works... although the views for all the games I tried so far were unusable.

**Comment by jshslsky** [comment]
It's probably like the Sauce Labs Selenium tool @stevenolen is using. They just boot up an Android image and run the app.

**Comment by jshslsky** [comment]
Closing because this is more of a nice to have and if we did it, it would add complexity to our project because we'd have to manage deploys to two app stores.
