### ISSUE TITLE
Ability for a campaign/survey author to configure survey triggers

### ISSUE THREAD

**Issue by irhs** [ohmage/android-lib#8]
The current code base only allows survey participants to set triggers of their choice for a survey of their choice. This is good for the user, but as a researcher I want to prompt for surveys to subjects at random times or specific times of my choice. 

Do you have any plans to add this capability?

**Comment by jshslsky** [comment]
When you set a user up on a phone for the first time, you can configure triggers to be at random times. (There are also location triggers if you haven't found those yet.)

As to your issue, this is something the ohmage team has discussed at length in the past. It is something we would consider adding to a given campaign's configuration, but this has ramifications across all of the users sharing a particular campaign.

One thing ohmage has is support for a JSON trigger config file. @cketcham can point you to the correct place to set that up.

**Comment by cketcham** [comment]
Any configuration you want built into your version of the app can be put in the /res/raw/triggers.json file. This file populates triggers for a campaign when it is downloaded to the phone.

Info for configuring this file can be found in the [TriggerInit.java](https://github.com/ohmage/ohmageAndroidLib/blob/master/src/org/ohmage/triggers/base/TriggerInit.java) file above the addDefaultTriggers function.

**Comment by irhs** [comment]
Thank you. This is helpful. 

Do you have any developers mailing group? Such queries seem more appropriate there.

**Comment by jshslsky** [comment]
We like to use GitHub because it helps to keep our technical discussions less fragmented. Some issues may turn into features or may be referenced to commits, etc.

**Comment by jshslsky** [comment]
This is part of the feature set for our 3.0 release.
