### ISSUE TITLE
Location reminder doesn't trigger when reaching the location

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#84]
When I reach the location, the reminder didn't trigger on the device (both phone 2.3.6 and tablet 4.1.2)

[Edit: Log has been removed because we don't need it for this issue.]

**Comment by jshslsky** [comment]
To fix, we should be using Google's new geo-fencing API. This has been marked as 2.16 and we can take a look if someone running 2.16 needs more accurate location triggers.
