### ISSUE TITLE
problems with video prompt

### ISSUE THREAD

**Issue by jshslsky** [ohmage/android-lib#87]
I am using the Video Test campaign. If I take a video, "Please take a video of something before continuing." appears even though I had recorded it already. The app then enters a strange state where sometimes the message appears on the dashboard. Weirdly, on one of my tests I was also able to upload a video even though I saw the message.

**Comment by cketcham** [comment]
this appears to be a bug on some nexus devices. but there is a work around. https://code.google.com/p/android/issues/detail?id=57996
