### ISSUE TITLE
photo prompt does not obey maxDimension property

### ISSUE THREAD

**Issue by jshslsky** [ohmage/android-lib#89]
I am trying to estimate server disk usage and when I use the photo testing campaign, all of the landscape images were 816x612 and portraits were 612x816. Is this the expected behavior? 

[This is the campaign](https://github.com/ohmage/ohmageConfiguration/blob/master/campaign_xml/photo_test.xml).

**Comment by cketcham** [comment]
I checked that campaign and noticed that the parameter which is defined is 'res' but it should be 'maxDimension'. Was 'res' ever a valid parameter? or did we just use res while testing and the campaign xml was never updated?

**Comment by jshslsky** [comment]
`res` was the old value we used. At some point we upgraded to `maxDimension`.

Can you explain why the images are all being resized? If I take a photo with the stock camera app it's 2.5 MB. With ohmage, a very similar photo is 124 KB.

**Comment by cketcham** [comment]
the default is to resize the image to be smaller than 800px on the long side

**Comment by jshslsky** [comment]
Huh. So that means we should just get rid of `maxDimension` then and document the way it works.

**Comment by cketcham** [comment]
no, it works with maxDimension, but the campaign xml for that campaign
incorrectly specifies 'res'. and because it doesn't specify maxDimension it
defaults to 800px

**Comment by jshslsky** [comment]
OK, then we have a documentation task unless you have already documented this.

**Comment by cketcham** [comment]
on the ohmageServer wiki it is already documented as being maxDimension

**Comment by hongsudt** [comment]
Yea.. and if I remember correctly, since we have many campaigns that use
"res", we have a default of maxDimension=800 if it is not provided.

**Comment by jshslsky** [comment]
@cketcham I meant that we should document what the Android app does when maxDimension is missing.

**Comment by cketcham** [comment]
updated the docs
