### ISSUE TITLE
'Message prompt' conditions are not working properly

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#92]
On test.ohmage.org, campaign '1082013 Msg Condition' has a message prompt that has condition below:

<message>
    <id>m2</id>
    <messageText>m2</messageText>
    <condition>(p1 == 1)</condition>
</message>

If my response on p1 is 0 the message prompt still shows...then if I go back and tapped 'previous' button without changing my response (still 0)...that's the only time the message prompt doesn't show.

Also, if I include a message prompt in a condition the prompt won't regardless if the condition was met or not

<prompt>
    <id>p5</id>
    <displayLabel>p5</displayLabel>
    <promptText>p5</promptText>
    <promptType>text</promptType>
    <condition>(p3 == 5 and m2 != NOT_DISPLAYED and p4 == 0)</condition>
    <skippable>false</skippable>
    <properties>
        <property>
            <key>min</key>
            <label>0</label>
        </property>
        <property>
            <key>max</key>
            <label>100</label>
        </property>
    </properties>
</prompt>

**Comment by ctrance** [comment]
@cketcham - Where can I get the fixed apk for this issue? So I can retest...

**Comment by cketcham** [comment]
the apk here https://web.ohmage.org/ohmage/apk/ohmage-latest.apk has been updated.

**Comment by ctrance** [comment]
@cketcham - The text prompt p5 has this condition (p3 == 5 and m2 != NOT_DISPLAYED and p4 == 0), my responses (p3=5, m2 is displayed, p4=0) met the condition but the text prompt still didn't show. You can use this campaign ''1082013 Msg Condition'
