### ISSUE TITLE
Should prompts be allowed to condition on if messages were displayed or not?

### ISSUE THREAD

**Issue by cketcham** [ohmage/android-lib#95]
This issue was brought up in #92.

Consider a Survey with 1 prompt followed by two messages. If the value of the prompt == 1, then the first message should be shown. If message1 == NOT_DISPLAYED, then the second message should be shown.

This is allowed by the server, but the phone doesn't handle it since whoever wrote the condition evaluator didn't allow messages to have values. So when the condition is computed it will always be false since message1 doesn't have a value.

It could be useful to allow it since people might try to do it, by why not just condition on the value of the first prompt. (ie. prompt != 1) instead of if the message is shown or not.

Either the phone needs to allow it, or the server should reject conditioning against the value of messages. Or we could just ignore it in 2.x since it probably won't happen very frequently.

**Comment by cketcham** [comment]
Its not super easy to fix this bug on the phone. If we need it, we can do it at some in the future.

**Comment by cketcham** [comment]
@jojenki, @hongsudt and I were talking and we think it might be best to prevent people from conditioning on if messages were shown or not on the server to prevent confusion. Since we don't support it on the phone (and it would be more work to add it on the phone), it shouldn't be allowed to pass validation. It should probably also show an error message to the user which tells them to take the condition for if the message was shown or not instead of conditioning on not displayed or displayed.

**Comment by jshslsky** [comment]
We can fix this if the issue actually comes up in practice. Go go go 3.0.

**Comment by hongsudt** [comment]
Doesn't the server already have this validation rule, and we just have to
uncomment it?

This issue came up because Cathy (who is an average user) creates a
campaign with a condition on whether a message is displayed.. And it killed
both the mwf and native android. Mwf displayed the wrong sequence and
couldn't upload the response.. Native showed the wrong sequence but was
able to upload the response.  I start to get people to use the campaign
authoring tool and expect we might get more of these cases in the future
since it is easier for people to create their own campaigns :)

**Comment by jojenki** [comment]
For the record, my position was the opposite. Someone should be able to
condition off of whether or not a message was displayed/skipped.

**Comment by cketcham** [comment]
I agree for 3.0 we should allow it, but for 2.x we should do something that is the least amount of work but is also consistent. It seems that it is easiest to prevent users from conditioning on if a message was displayed.

**Comment by hongsudt** [comment]
I totally agree with you. We should make sure that 3.0 can support this.

For 2.x, I can go with either 1) server validates that message is not part
of the conditional statement, so that we won't be in the situation that I
mentioned earlier, or 2) get the phones to support them (both native and
mwf).  Since 1) seems to be less amount of work, I opted for that one :)

**Comment by jshslsky** [comment]
OK, I have fixed this. When this gets deployed, it will cause the server to fail to start up if any of the campaigns on that server contain conditions containing message ids. @stevenolen does Jenkins still deploy pushes to 2.16 to otest?

**Comment by jshslsky** [comment]
I typed too fast last night. This fix won't cause the server to fail on startup, but any users who belong to campaigns with conditions based on message ids will not be able to login.

**Comment by hongsudt** [comment]
Got it. Will ask Cathy to remove those surveys and retest..

**Comment by jshslsky** [comment]
The new build is on otest.

**Comment by jshslsky** [comment]
@hongsudt she won't be able to login. Do you know the URN or the name of the campaign that has the conditions based on messages?

**Comment by hongsudt** [comment]
It is the campaign '1082013 Msg Condition' .

@ctrance are there other campaigns with message conditions?

**Comment by jshslsky** [comment]
I removed that one, but there are others.

**Comment by ctrance** [comment]
I don't remember the other campaigns (couldn't see anything after the login), but I think you can remove campaigns that have title '10/../2013...'.

**Comment by jshslsky** [comment]
OK, there are also older campaigns that have this issue. I am going through the list.

**Comment by jshslsky** [comment]
All of the offending campaigns have been removed from otest. All of them except one were small tests from @ctrance. The other one was a condition tester campaign that @jojenki wrote. I removed that one from the DB on otest, but it's still in GitHub.
