### ISSUE TITLE
We should maintain backwards compatibility for number prompts

### ISSUE THREAD

**Issue by cketcham** [ohmage/android-lib#96]
Since there are many campaigns which are currently in use and rely on values from number prompts being whole numbers, decimal values should not be allowed by default.

Currently the parameter which specifies if a number prompt must be a whole number is called wholeNumber. If whole number is true, decimal values are not allowed. It is odd to set a default boolean value to true, so it might make more sense to change this parameter name to decimalNumber instead of wholeNumber, and to default that to false.

@jojenki @joshuaselsky what do you think? It would require a change on the server, but I think it would be more intuitive and could potentially prevent problems in the future to change the parameter to decimalNumber. Instead of creating a new campaign and omitting the wholeNumber parameter and accidentally only being able to get whole numbers, they will omit the decimalNumber parameter and only get whole numbers. Although it would be quicker for now to just change the default on the phone to true... so I'm not sure which to do.

**Comment by jojenki** [comment]
What's the harm in having it allow decimal numbers by default?

**Comment by cketcham** [comment]
the visualization and analysis components of campaigns that already exist depend on them being whole numbers...

**Comment by jshslsky** [comment]
This is not critical and we don't have the cycles to fix it right now. Maybe later.

**Comment by hongsudt** [comment]
Cameron,
then as a temporary solution, can you change the default value of
wholeNumber to true, instead of false?  This will be a simple change and
allow backward compatibility.

Thanks,

**Comment by jshslsky** [comment]
Maybe at some time in the future, but not soon.

**Comment by jshslsky** [comment]
@cketcham can you let @stevenolen the file that needs to be changed?

We'll have to redeploy both the ohamge and the Mobilize apps in Google Play.

**Comment by cketcham** [comment]
I decided to just go ahead and push the change.. but I didn't build or test it. So @stevenolen can you do that for me? thanks for your help!
