### ISSUE TITLE
Multi-choice/Multi-choice custom prompt shows no warning when moving forward without a selected choice

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#97]
I tap 'next' button without selecting any item from the multi-choice/multi-choice custom prompt the app didn't warn me to either select an item or tap skip button instead. I tried doing the same on single-choice prompt but the app warned me to 'please select an item'. Please apply the same validation to multi-choice prompt.

**Comment by ctrance** [comment]
@cketcham - where can I get the latest apk again?

**Comment by cketcham** [comment]
this should work https://web.ohmage.org/ohmage/apk/2.0/ohmage-latest.apk
