### ISSUE TITLE
turn off LogProbe for otest

### ISSUE THREAD

**Issue by jshslsky** [ohmage/android-lib#99]
We've never used the data and the volume of data has created performance problems for any kind of stream data.

**Comment by cketcham** [comment]
should I stop logprobe everywhere? We are currently logging errors on play.ohmage.org and pilots.mobilizelabs.org, and everything on lausd.mobilizingcs.org, dev.ohmage.org and  test.ohmage.org.

One option is to just log errors? can we see how much space that is taking up on play.ohmage.org?

**Comment by hongsudt** [comment]
Is there a way to rearrange the log message to be more of a row based
format? Eg turning 5 small records into one long record?

I think logs are useful. We just have to figure out how to make it work...

**Comment by jshslsky** [comment]
- dev.ohmage.org isn't relevant for 2.16 anymore
- test.ohmage.org should only log errors
- For LAUSD, I will leave it up to @hongsudt

**Comment by cketcham** [comment]
Only errors are logged
